package gui;

/**
 *
 * @author marcos
 */
public class AttributeObjectPanel extends AttributePanel {

    private project.Project projectBean;

    /** Creates new form AttributeObjectPanel */
    public AttributeObjectPanel(project.Project projectBean, project.ClassBean classBean) {
        this.projectBean = projectBean;
        initComponents();

        //atualiza lista de classes
        for(project.ClassBean classBeanItem: projectBean.getClassBeans()){
            if(classBeanItem != classBean && !classBeanItem.getUnique().isEmpty())
                cClassRef.addItem(classBeanItem.getName());
        }
    }

    @Override
    public void setAtribute(project.Attribute attribute){
        project.AttributeObject attObject = (project.AttributeObject)attribute;
        cClassRef.setSelectedItem(attObject.getClassRef());
        cAttribLookUp.setSelectedItem(attObject.getAttribLookUp());
    }

    @Override
    public project.AttributeObject getAtribute(){
        project.AttributeObject att = new project.AttributeObject();
        att.setClassRef(cClassRef.getSelectedItem().toString());
        att.setAttribLookUp(cAttribLookUp.getSelectedItem().toString());
        return att;
    }

    @Override
    public String validateForm(){
        String error = "";
        if(cClassRef.getSelectedItem()==null) error+= "Classe de referência\n";
        if(cAttribLookUp.getSelectedItem()==null) error+= "Atributo de visualização\n";
        return error;
    }

     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLabels = new javax.swing.JPanel();
        lClassRef = new javax.swing.JLabel();
        lAttribLookUp = new javax.swing.JLabel();
        pFields = new javax.swing.JPanel();
        cClassRef = new javax.swing.JComboBox();
        cAttribLookUp = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout(10, 0));

        pLabels.setPreferredSize(new java.awt.Dimension(150, 51));
        pLabels.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        lClassRef.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lClassRef.setText("Classe de referência");
        pLabels.add(lClassRef);

        lAttribLookUp.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lAttribLookUp.setText("Atributo de visualização");
        pLabels.add(lAttribLookUp);

        add(pLabels, java.awt.BorderLayout.WEST);

        pFields.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        cClassRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cClassRefActionPerformed(evt);
            }
        });
        pFields.add(cClassRef);
        pFields.add(cAttribLookUp);

        add(pFields, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cClassRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cClassRefActionPerformed
        if(cClassRef.getSelectedItem()!=null){
            cAttribLookUp.setSelectedItem(null);
            cAttribLookUp.removeAllItems();
            java.util.List<project.Attribute> attributes = projectBean.getClassBean(cClassRef.getSelectedItem().toString()).getAttributes();
            for(project.Attribute att: attributes){
                if(att.isUnique())
                    cAttribLookUp.addItem(att.getName());
            }
        }
    }//GEN-LAST:event_cClassRefActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cAttribLookUp;
    private javax.swing.JComboBox cClassRef;
    private javax.swing.JLabel lAttribLookUp;
    private javax.swing.JLabel lClassRef;
    private javax.swing.JPanel pFields;
    private javax.swing.JPanel pLabels;
    // End of variables declaration//GEN-END:variables
}
