package gui;

/**
 *
 * @author marcos
 */
public class AttributePanel extends javax.swing.JPanel {

    /** Creates new form AttributeBooleanPanel */
    public AttributePanel() {
        initComponents();
    }

    public void setAtribute(project.Attribute attribute){
    }
    
    public project.Attribute getAtribute(){
        project.Attribute att = new project.Attribute();
        return att;
    }

    public String validateForm(){
        String error = "";
        return error;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout(10, 0));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
