package gui;

/**
 *
 * @author marcos
 */
public class AttributeStringPanel extends AttributePanel {

    private AttributeForm parent;
    private project.Project projectBean;
    private project.ClassBean classBean;

    /** Creates new form AttributeStringPanel */
    public AttributeStringPanel(AttributeForm parent, project.Project projectBean, project.ClassBean classBean) {
        this.parent = parent;
        this.projectBean = projectBean;
        this.classBean = classBean;
        initComponents();
    }

    @Override
    public void setAtribute(project.Attribute attribute){
        project.AttributeString attString = (project.AttributeString)attribute;
        cKey.setSelectedItem(attString.getKey());
        tStartValue.setText(attString.getStartValue());
        tLength.setText(""+attString.getLength());
        tMaskFormat.setText(attString.getMaskFormat());
        
        //Verifica se está sendo utilizado por outras classes do projeto
        if(classBean.isUsed(projectBean)){
            Boolean useThis = false;
            java.util.List<project.ClassBean> classesUses = classBean.getClassesUses(projectBean);
            for(project.ClassBean c : classesUses){
                java.util.List<project.Attribute> atts = c.getAttributesOfType(project.Attribute.Type.OBJECT);
                for(project.Attribute att : atts){
                    project.AttributeObject attObj = (project.AttributeObject)att;
                    if(attObj.getClassRef().compareTo(classBean.getName())==0 &&
                       attObj.getAttribLookUp().compareTo(attString.getName())==0){
                        useThis = true;
                    }
                }
            }
            //Se está sendo utilizado desabilita a edição dos campos
            if(useThis){
                parent.setEditable(false);
                cKey.setEnabled(false);
            } else {
                parent.setEditable(true);
                cKey.setEnabled(true);
            }
        }
    }

    @Override
    public project.AttributeString getAtribute(){
        project.AttributeString att = new project.AttributeString();
        att.setKey((project.AttributeString.KeyType)cKey.getSelectedItem());
        att.setStartValue(tStartValue.getText());
        att.setLength(Integer.parseInt(tLength.getText()));
        att.setMaskFormat(tMaskFormat.getText());
        return att;
    }

    @Override
    public String validateForm(){
        String error = "";
        if(cKey.getSelectedItem()==null) error+= "Tipo chave\n";
        if(Integer.parseInt(tLength.getText())<=0) error+= "Comprimento\n";
        return error;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLabels = new javax.swing.JPanel();
        lName = new javax.swing.JLabel();
        lStartValue = new javax.swing.JLabel();
        lLength = new javax.swing.JLabel();
        lMaskFormat = new javax.swing.JLabel();
        pFields = new javax.swing.JPanel();
        cKey = new javax.swing.JComboBox(project.AttributeString.KeyType.values());
        tStartValue = new javax.swing.JFormattedTextField();
        tLength = new javax.swing.JFormattedTextField();
        tMaskFormat = new javax.swing.JFormattedTextField();

        pLabels.setPreferredSize(new java.awt.Dimension(150, 51));
        pLabels.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        lName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lName.setText("Tipo de Chave");
        pLabels.add(lName);

        lStartValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lStartValue.setText("Valor Inicial");
        pLabels.add(lStartValue);

        lLength.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lLength.setText("Comprimento");
        pLabels.add(lLength);

        lMaskFormat.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lMaskFormat.setText("Formato da máscara");
        pLabels.add(lMaskFormat);

        add(pLabels, java.awt.BorderLayout.WEST);

        pFields.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        cKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKeyActionPerformed(evt);
            }
        });
        pFields.add(cKey);
        pFields.add(tStartValue);

        tLength.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tLength.setText("20");
        pFields.add(tLength);
        pFields.add(tMaskFormat);

        add(pFields, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKeyActionPerformed
        if(cKey.getSelectedItem()!=null){
            if(cKey.getSelectedIndex()==project.AttributeString.KeyType.UNIQUE.ordinal()){
                tStartValue.setEnabled(false);
                tStartValue.setFocusable(false);
            } else {
                tStartValue.setEnabled(true);
                tStartValue.setFocusable(true);
            }
        }
    }//GEN-LAST:event_cKeyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cKey;
    private javax.swing.JLabel lLength;
    private javax.swing.JLabel lMaskFormat;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lStartValue;
    private javax.swing.JPanel pFields;
    private javax.swing.JPanel pLabels;
    private javax.swing.JFormattedTextField tLength;
    private javax.swing.JFormattedTextField tMaskFormat;
    private javax.swing.JFormattedTextField tStartValue;
    // End of variables declaration//GEN-END:variables
}
