package gui;

/**
 *
 * @author marcos
 */
public class AttributeFixedListPanel extends AttributePanel {

    /** Creates new form AttributeFixedListPanel */
    public AttributeFixedListPanel() {
        initComponents();
    }

    @Override
    public void setAtribute(project.Attribute attribute){
        project.AttributeFixedList attFixedList = (project.AttributeFixedList)attribute;
        cTypeStore.setSelectedItem(attFixedList.getTypeStore());
        tListOptions.setText(attFixedList.getListOptions());
    }
    @Override
    public project.AttributeFixedList getAtribute(){
        project.AttributeFixedList att = new project.AttributeFixedList();
        att.setTypeStore((project.AttributeFixedList.TypeStore)cTypeStore.getSelectedItem());
        att.setListOptions(tListOptions.getText());
        return att;
    }
    @Override
    public String validateForm(){
        String error = "";
        
        if(cTypeStore.getSelectedItem()==null) error+= "Tipo de armazenamento\n";
        if(tListOptions.getText().length()==0) error+= "Lista de opções\n";
        
        return error;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pLabels = new javax.swing.JPanel();
        lTypeStore = new javax.swing.JLabel();
        lListOptions = new javax.swing.JLabel();
        pFields = new javax.swing.JPanel();
        cTypeStore = new javax.swing.JComboBox(project.AttributeFixedList.TypeStore.values());
        jPanel2 = new javax.swing.JPanel();
        sListOptions = new javax.swing.JScrollPane();
        tListOptions = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout(10, 0));

        jPanel1.setLayout(new java.awt.BorderLayout(10, 0));

        pLabels.setPreferredSize(new java.awt.Dimension(150, 51));
        pLabels.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        lTypeStore.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lTypeStore.setText("Armazenamento por");
        pLabels.add(lTypeStore);

        lListOptions.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lListOptions.setText("Lista de opções");
        pLabels.add(lListOptions);

        jPanel1.add(pLabels, java.awt.BorderLayout.WEST);

        pFields.setLayout(new java.awt.GridLayout(2, 0, 0, 5));
        pFields.add(cTypeStore);

        jPanel1.add(pFields, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        tListOptions.setColumns(20);
        tListOptions.setRows(8);
        sListOptions.setViewportView(tListOptions);

        jPanel2.add(sListOptions);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cTypeStore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lListOptions;
    private javax.swing.JLabel lTypeStore;
    private javax.swing.JPanel pFields;
    private javax.swing.JPanel pLabels;
    private javax.swing.JScrollPane sListOptions;
    private javax.swing.JTextArea tListOptions;
    // End of variables declaration//GEN-END:variables
}
