/*
 * AttributeIdentity.java
 *
 * Created on 19/06/2011, 15:05:04
 */
package gui;

/**
 *
 * @author marcos
 */
public class AttributeIntegerPanel extends AttributePanel {

    private AttributeForm parent;
    private project.Project projectBean;
    private project.ClassBean classBean;

    /** Creates new form AttributeIdentity */
    public AttributeIntegerPanel(AttributeForm parent, project.Project projectBean, project.ClassBean classBean) {
        this.parent = parent;
        this.projectBean = projectBean;
        this.classBean = classBean;
        initComponents();
    }

    @Override
    public void setAtribute(project.Attribute attribute){
        project.AttributeInteger attInteger = (project.AttributeInteger) attribute;
        cKey.setSelectedItem(attInteger.getKey());
        tStartValue.setText(""+attInteger.getStartValue());
        //Verifica se está sendo utilizado por outras classes do projeto
        if(classBean.isUsed(projectBean)){
            Boolean useThis = false;
            java.util.List<project.ClassBean> classesUses = classBean.getClassesUses(projectBean);
            for(project.ClassBean c : classesUses){
                java.util.List<project.Attribute> atts = c.getAttributesOfType(project.Attribute.Type.OBJECT);
                for(project.Attribute att : atts){
                    project.AttributeObject attObj = (project.AttributeObject)att;
                    if(attObj.getClassRef().compareTo(classBean.getName())==0 &&
                       attObj.getAttribLookUp().compareTo(attInteger.getName())==0){
                        useThis = true;
                    }
                }
            }
            //Se está sendo utilizado desabilita a edição dos campos
            if(useThis){
                parent.setEditable(false);
                cKey.setEnabled(false);
            } else {
                parent.setEditable(true);
                cKey.setEnabled(true);
            }
        }
    }
    
    @Override
    public project.AttributeInteger getAtribute(){
        project.AttributeInteger att = new project.AttributeInteger();
        att.setKey((project.AttributeInteger.KeyType)cKey.getSelectedItem());
        att.setStartValue(Integer.parseInt(tStartValue.getText()));
        return att;
    }

    @Override
    public String validateForm(){
        String error = "";
        if(cKey.getSelectedItem()==null) error+= "Tipo chave\n";
        if(tStartValue.getText().length()==0) error+= "Valor Inicial\n";
        return error;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLabels = new javax.swing.JPanel();
        lName = new javax.swing.JLabel();
        lStartValue = new javax.swing.JLabel();
        pFields = new javax.swing.JPanel();
        cKey = new javax.swing.JComboBox(project.AttributeInteger.KeyType.values());
        tStartValue = new javax.swing.JFormattedTextField();

        pLabels.setPreferredSize(new java.awt.Dimension(150, 51));
        pLabels.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        lName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lName.setText("Tipo de Chave");
        pLabels.add(lName);

        lStartValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lStartValue.setText("Valor Inicial");
        pLabels.add(lStartValue);

        add(pLabels, java.awt.BorderLayout.WEST);

        pFields.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        cKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKeyActionPerformed(evt);
            }
        });
        pFields.add(cKey);

        tStartValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tStartValue.setText("0");
        pFields.add(tStartValue);

        add(pFields, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKeyActionPerformed
        if(cKey.getSelectedItem()!=null){
            if(cKey.getSelectedIndex()==project.AttributeInteger.KeyType.UNIQUE.ordinal()){
                tStartValue.setEnabled(false);
                tStartValue.setFocusable(false);
            } else {
                tStartValue.setEnabled(true);
                tStartValue.setFocusable(true);
            }
        }
    }//GEN-LAST:event_cKeyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cKey;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lStartValue;
    private javax.swing.JPanel pFields;
    private javax.swing.JPanel pLabels;
    private javax.swing.JFormattedTextField tStartValue;
    // End of variables declaration//GEN-END:variables
}
