package gui;

/**
 *
 * @author marcos
 */
public class AttributeImagePanel extends AttributePanel {

    /** Creates new form AttributeImagePanel */
    public AttributeImagePanel() {
        initComponents();
    }

    @Override
    public void setAtribute(project.Attribute attribute){
        project.AttributeImage attImage = (project.AttributeImage)attribute;
        cFixedWidth.setSelected(attImage.isFixedWidth());
        tWidth.setText(""+attImage.getWidth());
    }

    @Override
    public project.AttributeImage getAtribute(){
        project.AttributeImage att = new project.AttributeImage();
        att.setFixedWidth(cFixedWidth.isSelected());
        att.setWidth(Integer.parseInt(tWidth.getText()));
        return att;
    }

    @Override
    public String validateForm(){
        String error = "";
        if(Integer.parseInt(tWidth.getText())<0) error+= "Largura\n";
        return error;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLabels = new javax.swing.JPanel();
        lFixedWidth = new javax.swing.JLabel();
        lWidth = new javax.swing.JLabel();
        pFields = new javax.swing.JPanel();
        cFixedWidth = new javax.swing.JCheckBox();
        tWidth = new javax.swing.JFormattedTextField();

        setLayout(new java.awt.BorderLayout(10, 0));

        pLabels.setPreferredSize(new java.awt.Dimension(150, 51));
        pLabels.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        lFixedWidth.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lFixedWidth.setText("Largura fixa");
        pLabels.add(lFixedWidth);

        lWidth.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lWidth.setText("Largura");
        pLabels.add(lWidth);

        add(pLabels, java.awt.BorderLayout.WEST);

        pFields.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        cFixedWidth.setSelected(true);
        cFixedWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFixedWidthActionPerformed(evt);
            }
        });
        pFields.add(cFixedWidth);

        tWidth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tWidth.setText("200");
        pFields.add(tWidth);

        add(pFields, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cFixedWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFixedWidthActionPerformed
        if(cFixedWidth.isSelected()){
            lWidth.setVisible(true);
            tWidth.setVisible(true);
        } else {
            lWidth.setVisible(false);
            tWidth.setVisible(false);
        }
    }//GEN-LAST:event_cFixedWidthActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cFixedWidth;
    private javax.swing.JLabel lFixedWidth;
    private javax.swing.JLabel lWidth;
    private javax.swing.JPanel pFields;
    private javax.swing.JPanel pLabels;
    private javax.swing.JFormattedTextField tWidth;
    // End of variables declaration//GEN-END:variables
}
