/*
 * AttributeTimePanel.java
 *
 * Created on 19/06/2011, 15:05:04
 */
package gui;

/**
 *
 * @author marcos
 */
public class AttributeTimePanel extends AttributePanel {

    /** Creates new form AttributeTimePanel */
    public AttributeTimePanel() {
        initComponents();
    }

    @Override
    public void setAtribute(project.Attribute attribute){
        project.AttributeTime attTime = (project.AttributeTime)attribute;
        cIndexed.setSelected(attTime.isIndexed());
        cUseCurrentTime.setSelected(attTime.isUseCurrentTime());
    }
    @Override
    public project.AttributeTime getAtribute(){
        project.AttributeTime att = new project.AttributeTime();
        att.setIndexed(cIndexed.isSelected());
        att.setUseCurrentTime(cUseCurrentTime.isSelected());
        return att;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLabels = new javax.swing.JPanel();
        lName = new javax.swing.JLabel();
        lUseCurrentTime = new javax.swing.JLabel();
        pFields = new javax.swing.JPanel();
        cIndexed = new javax.swing.JCheckBox();
        cUseCurrentTime = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout(10, 0));

        pLabels.setPreferredSize(new java.awt.Dimension(150, 51));
        pLabels.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        lName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lName.setText("Tipo de Chave");
        pLabels.add(lName);

        lUseCurrentTime.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lUseCurrentTime.setText("Usar hora atual");
        pLabels.add(lUseCurrentTime);

        add(pLabels, java.awt.BorderLayout.WEST);

        pFields.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        cIndexed.setText("Indexado");
        pFields.add(cIndexed);
        pFields.add(cUseCurrentTime);

        add(pFields, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cIndexed;
    private javax.swing.JCheckBox cUseCurrentTime;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lUseCurrentTime;
    private javax.swing.JPanel pFields;
    private javax.swing.JPanel pLabels;
    // End of variables declaration//GEN-END:variables
}
