package gui;

/**
 *
 * @author marcos
 */
public class AttributeObjectListPanel extends AttributePanel {

    /** Creates new form AttributeObjectListPanel */
    public AttributeObjectListPanel(project.Project projectBean, project.ClassBean classBean) {
        initComponents();

        //atualiza lista de classes
        for(project.ClassBean classBeanItem: projectBean.getClassBeans()){
            if(classBean != classBeanItem && 
              !classBeanItem.getUnique().isEmpty() && 
              !classBeanItem.isDependent(projectBean))
                cClassRef.addItem(classBeanItem.getName());
        }
    }

    @Override
    public void setAtribute(project.Attribute attribute){
        project.AttributeObjectList attObjectList = (project.AttributeObjectList)attribute;
        if(!attObjectList.getClassRef().isEmpty()) cClassRef.addItem(attObjectList.getClassRef());
        cClassRef.setSelectedItem(attObjectList.getClassRef());
    }

    @Override
    public project.AttributeObjectList getAtribute(){
        project.AttributeObjectList att = new project.AttributeObjectList();
        att.setClassRef(cClassRef.getSelectedItem().toString());
        return att;
    }

    @Override
     public String validateForm(){
        String error = "";
        if(cClassRef.getSelectedItem()==null) error+= "Classe de referência\n";
        return error;
    }

     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLabels = new javax.swing.JPanel();
        lClassRef = new javax.swing.JLabel();
        pFields = new javax.swing.JPanel();
        cClassRef = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout(10, 0));

        pLabels.setPreferredSize(new java.awt.Dimension(150, 51));
        pLabels.setLayout(new java.awt.GridLayout(2, 0));

        lClassRef.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lClassRef.setText("Classe de referência");
        pLabels.add(lClassRef);

        add(pLabels, java.awt.BorderLayout.WEST);

        pFields.setLayout(new java.awt.GridLayout(2, 0));
        pFields.add(cClassRef);

        add(pFields, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cClassRef;
    private javax.swing.JLabel lClassRef;
    private javax.swing.JPanel pFields;
    private javax.swing.JPanel pLabels;
    // End of variables declaration//GEN-END:variables
}
