package gui;

/**
 *
 * @author marcos
 */
public class AttributeForm extends javax.swing.JDialog {

    private project.Attribute attribute;
    private project.ClassBean classBean;
    private project.Project projectBean;
    private java.util.List<AttributePanel> panels;

    /** Creates new form AttributeForm */
    public AttributeForm(java.awt.Window parent, project.Project projectBean, project.ClassBean classBean, project.Attribute attribute) {
        super(parent);
        this.projectBean = projectBean;
        this.classBean = classBean;
        this.attribute = attribute;
        this.panels = new java.util.ArrayList<AttributePanel>();
        this.panels.add(new AttributePanel());
        this.panels.add(new AttributeIdentityPanel(this, projectBean, this.classBean));
        this.panels.add(new AttributeIntegerPanel(this, projectBean, this.classBean));
        this.panels.add(new AttributeFloatPanel());
        this.panels.add(new AttributeBooleanPanel());
        this.panels.add(new AttributeStringPanel(this, projectBean, this.classBean));
        this.panels.add(new AttributeDatePanel());
        this.panels.add(new AttributeTimePanel());
        this.panels.add(new AttributeImagePanel());
        this.panels.add(new AttributeFixedListPanel());
        this.panels.add(new AttributeObjectPanel(projectBean, this.classBean));
        this.panels.add(new AttributeObjectListPanel(projectBean, this.classBean));
        initComponents();
        this.setTitle("Atributo da classe "+classBean.getName());
    }

    private void obj2form() {
        tName.setText(attribute.getName());
        tDescription.setText(attribute.getDescription());
        cType.setSelectedItem(attribute.getType());
        panels.get(cType.getSelectedIndex()).setAtribute(attribute);
    }

    private void form2obj() {
        if (attribute != null) {
            String name = attribute.getName();
            attribute = panels.get(cType.getSelectedIndex()).getAtribute();
            attribute.setName(name);
            attribute.rename(projectBean, classBean, tName.getText());
            attribute.setDescription(tDescription.getText());
        }
    }

    private String validadeForm() {
        String error = "";
        if (tName.getText().isEmpty()) error += "Nome\n";
        if (classBean.hasAttribute(tName.getText()) && attribute.getName().isEmpty()) error += "Nome de atributo já existente\n";
        if (cType.getSelectedItem().equals(project.Attribute.Type.NONE)) error += "Tipo\n";
        error += panels.get(cType.getSelectedIndex()).validateForm();
        return error;
    }

    public project.Attribute showInputDialog() {
        //carrega os dados dos atributos 
        obj2form();
        //Mostra o form
        this.setVisible(true);
        //Após ocultar o form salva
        form2obj();
        this.dispose();
        return this.attribute;
    }

    public void setEditable(Boolean editable){
        if(editable){
            //tName.setEditable(true);
            cType.setEnabled(true);
        } else {
            //tName.setEditable(false);
            cType.setEnabled(false);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAttribute = new javax.swing.JPanel();
        pAttributeFields = new javax.swing.JPanel();
        pLabels = new javax.swing.JPanel();
        lName = new javax.swing.JLabel();
        lType = new javax.swing.JLabel();
        lDescription = new javax.swing.JLabel();
        pFields = new javax.swing.JPanel();
        tName = new javax.swing.JTextField();
        cType = new javax.swing.JComboBox(project.Attribute.Type.values());
        tDescription = new javax.swing.JTextField();
        pAttributeType = new javax.swing.JPanel();
        pButtons = new javax.swing.JPanel();
        bOk = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(0, 5));

        pAttribute.setLayout(new java.awt.BorderLayout(0, 5));

        pAttributeFields.setLayout(new java.awt.BorderLayout(10, 0));

        pLabels.setPreferredSize(new java.awt.Dimension(150, 79));
        pLabels.setLayout(new java.awt.GridLayout(3, 0, 0, 5));

        lName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lName.setText("Nome");
        pLabels.add(lName);

        lType.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lType.setText("Tipo");
        pLabels.add(lType);

        lDescription.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lDescription.setText("Descrição");
        pLabels.add(lDescription);

        pAttributeFields.add(pLabels, java.awt.BorderLayout.WEST);

        pFields.setLayout(new java.awt.GridLayout(3, 0, 0, 5));
        pFields.add(tName);

        cType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTypeActionPerformed(evt);
            }
        });
        pFields.add(cType);
        pFields.add(tDescription);

        pAttributeFields.add(pFields, java.awt.BorderLayout.CENTER);

        pAttribute.add(pAttributeFields, java.awt.BorderLayout.NORTH);

        pAttributeType.setLayout(new java.awt.BorderLayout(10, 0));
        pAttribute.add(pAttributeType, java.awt.BorderLayout.CENTER);

        getContentPane().add(pAttribute, java.awt.BorderLayout.CENTER);

        bOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_calc-accept-16.png"))); // NOI18N
        bOk.setMnemonic('O');
        bOk.setText("      Ok      ");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });
        pButtons.add(bOk);

        bCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_calc-cancel-16.png"))); // NOI18N
        bCancel.setMnemonic('C');
        bCancel.setText("   Cancel   ");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        pButtons.add(bCancel);

        getContentPane().add(pButtons, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(410, 342));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTypeActionPerformed
        pAttributeType.removeAll();
        pAttributeType.add(panels.get(cType.getSelectedIndex()), java.awt.BorderLayout.NORTH);
        if (( (cType.getSelectedItem().equals(project.Attribute.Type.OBJECT) ||
               cType.getSelectedItem().equals(project.Attribute.Type.OBJECT_LIST))&& 
              (projectBean.getClassBeans().size() - 1 == 0))
           || (cType.getSelectedItem().equals(project.Attribute.Type.OBJECT_LIST) &&
                classBean.getUnique().isEmpty())
           ) {
            pAttributeType.add(panels.get(0), java.awt.BorderLayout.NORTH);
            cType.setSelectedItem(project.Attribute.Type.NONE);
        }
        pAttributeType.revalidate();
        pAttributeType.repaint();
    }//GEN-LAST:event_cTypeActionPerformed

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        String error = validadeForm();
        if (error.length() == 0) {
            this.setVisible(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Dados incorretos!\nVerifique os seguintes campos:\n" + error, "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bOkActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        attribute = null;
        this.setVisible(false);
    }//GEN-LAST:event_bCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        bCancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOk;
    private javax.swing.JComboBox cType;
    private javax.swing.JLabel lDescription;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lType;
    private javax.swing.JPanel pAttribute;
    private javax.swing.JPanel pAttributeFields;
    private javax.swing.JPanel pAttributeType;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pFields;
    private javax.swing.JPanel pLabels;
    private javax.swing.JTextField tDescription;
    private javax.swing.JTextField tName;
    // End of variables declaration//GEN-END:variables
}
