package gui;

/**
 *
 * @author marcos
 */
public class AttributeBooleanPanel extends AttributePanel {

    /** Creates new form AttributeBooleanPanel */
    public AttributeBooleanPanel() {
        initComponents();
    }

    @Override
    public void setAtribute(project.Attribute attribute){
        project.AttributeBoolean attBoolean = (project.AttributeBoolean)attribute;
        cIndexed.setSelected(attBoolean.isIndexed());
        rTrue.setSelected(attBoolean.getInitialValue());
    }

    @Override
    public project.AttributeBoolean getAtribute(){
        project.AttributeBoolean att = new project.AttributeBoolean();
        att.setIndexed(cIndexed.isSelected());
        att.setInitialValue(rTrue.isSelected());
        return att;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gInitialValue = new javax.swing.ButtonGroup();
        pLabels = new javax.swing.JPanel();
        lKey = new javax.swing.JLabel();
        lInitialValue = new javax.swing.JLabel();
        pFields = new javax.swing.JPanel();
        cIndexed = new javax.swing.JCheckBox();
        pInitialValue = new javax.swing.JPanel();
        rTrue = new javax.swing.JRadioButton();
        rFalse = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout(10, 0));

        pLabels.setPreferredSize(new java.awt.Dimension(150, 51));
        pLabels.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        lKey.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lKey.setText("Tipo de Chave");
        pLabels.add(lKey);

        lInitialValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lInitialValue.setText("Valor Inicial");
        pLabels.add(lInitialValue);

        add(pLabels, java.awt.BorderLayout.WEST);

        pFields.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        cIndexed.setText("Indexado");
        pFields.add(cIndexed);

        pInitialValue.setLayout(new java.awt.GridLayout(1, 0));

        gInitialValue.add(rTrue);
        rTrue.setSelected(true);
        rTrue.setText("Verdadeiro");
        pInitialValue.add(rTrue);

        gInitialValue.add(rFalse);
        rFalse.setText("Falso");
        pInitialValue.add(rFalse);

        pFields.add(pInitialValue);

        add(pFields, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cIndexed;
    private javax.swing.ButtonGroup gInitialValue;
    private javax.swing.JLabel lInitialValue;
    private javax.swing.JLabel lKey;
    private javax.swing.JPanel pFields;
    private javax.swing.JPanel pInitialValue;
    private javax.swing.JPanel pLabels;
    private javax.swing.JRadioButton rFalse;
    private javax.swing.JRadioButton rTrue;
    // End of variables declaration//GEN-END:variables
}
