/*
 * AttributeFloatPanel.java
 *
 * Created on 19/06/2011, 15:05:04
 */
package gui;

/**
 *
 * @author marcos
 */
public class AttributeFloatPanel extends AttributePanel {

    /** Creates new form AttributeFloatPanel */
    public AttributeFloatPanel() {
        initComponents();
    }

    @Override
    public void setAtribute(project.Attribute attribute){
        project.AttributeFloat attFloat = (project.AttributeFloat)attribute;
        cIndexed.setSelected(attFloat.isIndexed());
        tStartValue.setText(attFloat.getStartValueF());
        tMaskFormat.setText(attFloat.getMaskFormat());
    }

    @Override
    public project.AttributeFloat getAtribute(){
        project.AttributeFloat att = new project.AttributeFloat();
        att.setIndexed(cIndexed.isSelected());
        att.setStartValueF(tStartValue.getText());
        att.setMaskformat(tMaskFormat.getText());
        return att;
    }

    @Override
    public String validateForm(){
        String error = "";
        if(tStartValue.getText().length()==0) error+= "Valor Inicial\n";
        return error;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLabels = new javax.swing.JPanel();
        lName = new javax.swing.JLabel();
        lStartValue = new javax.swing.JLabel();
        lMaskFormat = new javax.swing.JLabel();
        pFields = new javax.swing.JPanel();
        cIndexed = new javax.swing.JCheckBox();
        tStartValue = new javax.swing.JFormattedTextField();
        tMaskFormat = new javax.swing.JFormattedTextField();

        setLayout(new java.awt.BorderLayout(10, 0));

        pLabels.setPreferredSize(new java.awt.Dimension(150, 51));
        pLabels.setLayout(new java.awt.GridLayout(3, 0, 0, 5));

        lName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lName.setText("Tipo de Chave");
        pLabels.add(lName);

        lStartValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lStartValue.setText("Valor Inicial");
        pLabels.add(lStartValue);

        lMaskFormat.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lMaskFormat.setText("Formato da máscara");
        pLabels.add(lMaskFormat);

        add(pLabels, java.awt.BorderLayout.WEST);

        pFields.setLayout(new java.awt.GridLayout(3, 0, 0, 5));

        cIndexed.setText("Indexado");
        pFields.add(cIndexed);

        tStartValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.###"))));
        tStartValue.setText("0");
        pFields.add(tStartValue);

        tMaskFormat.setText("#,##0.###");
        pFields.add(tMaskFormat);

        add(pFields, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cIndexed;
    private javax.swing.JLabel lMaskFormat;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lStartValue;
    private javax.swing.JPanel pFields;
    private javax.swing.JPanel pLabels;
    private javax.swing.JFormattedTextField tMaskFormat;
    private javax.swing.JFormattedTextField tStartValue;
    // End of variables declaration//GEN-END:variables
}
