/*
  gui/JSQLGen5.java é parte do programa JSQLGen

 (c)Copyright 2005~2011 Marcos Morise.

    JSQLGen é um software livre; você pode redistribui-lo e/ou
    modifica-lo dentro dos termos da Licença Pública Geral GNU como
    publicada pela Fundação do Software Livre (FSF); na versão 3 da
    Licença.

    Este programa é distribuido na esperança que possa ser util,
    mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO
    a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
    Licença Pública Geral GNU para maiores detalhes.

    Você deve ter recebido uma cópia da Licença Pública Geral GNU
    junto com este programa, se não, veja em:
    <http://www.gnu.org/licenses/>
 */
package gui;

/**
 *
 * @author marcos
 */
public class JSQLGen5 extends javax.swing.JFrame {

    private java.util.List<ProjectPanel> projectsForm;
    private String currentDirectory = "./";
    private String version="5.4";

    /** Creates new form JSQLGen5 */
    public JSQLGen5() {
        super();
        this.projectsForm = new java.util.ArrayList<ProjectPanel>();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/jsqlgen_logo.png")).getImage());
        this.setTitle("JSQLGen "+version);
        initComponents();
        pProjects.setComponentPopupMenu(popupMenuProject);
        refreshMenuOptions();
        setVisible(true);
    }
    
    /**
     * Atualiza menus conforme projetos abertos
     */
    private void refreshMenuOptions(){
        if(pProjects.getComponentCount()==0){
            mSave.setEnabled(false);
            mSaveAs.setEnabled(false);
            mClose.setEnabled(false);
            mRename.setEnabled(false);
            mCodeGen.setEnabled(false);
            bSave.setEnabled(false);
            bClose.setEnabled(false);
            bRename.setEnabled(false);
            bCodeGen.setEnabled(false);
            mPopSave.setEnabled(false);
            mPopClose.setEnabled(false);
            mPopRename.setEnabled(false);
            mCut.setEnabled(false);
            mCopy.setEnabled(false);
            mPaste.setEnabled(false);
            bCut.setEnabled(false);
            bCopy.setEnabled(false);
            bPaste.setEnabled(false);
        } else {
            mSave.setEnabled(true);
            mSaveAs.setEnabled(true);
            mClose.setEnabled(true);
            mRename.setEnabled(true);
            mCodeGen.setEnabled(true);
            bSave.setEnabled(true);
            bClose.setEnabled(true);
            bRename.setEnabled(true);
            bCodeGen.setEnabled(true);
            mPopSave.setEnabled(true);
            mPopClose.setEnabled(true);
            mPopRename.setEnabled(true);
            mCut.setEnabled(true);
            mCopy.setEnabled(true);
            mPaste.setEnabled(true);
            bCut.setEnabled(true);
            bCopy.setEnabled(true);
            bPaste.setEnabled(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenuProject = new javax.swing.JPopupMenu();
        mPopNew = new javax.swing.JMenuItem();
        mPopOpen = new javax.swing.JMenuItem();
        mPopSave = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mPopRename = new javax.swing.JMenuItem();
        mPopClose = new javax.swing.JMenuItem();
        toolBar = new javax.swing.JToolBar();
        bNew = new javax.swing.JButton();
        bOpen = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        bRename = new javax.swing.JButton();
        bClose = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        bCodeGen = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        bCut = new javax.swing.JButton();
        bCopy = new javax.swing.JButton();
        bPaste = new javax.swing.JButton();
        pProjects = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        mNew = new javax.swing.JMenuItem();
        mOpen = new javax.swing.JMenuItem();
        mSave = new javax.swing.JMenuItem();
        mSaveAs = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mRename = new javax.swing.JMenuItem();
        mClose = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mCodeGen = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mExit = new javax.swing.JMenuItem();
        mEdit = new javax.swing.JMenu();
        mCut = new javax.swing.JMenuItem();
        mCopy = new javax.swing.JMenuItem();
        mPaste = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        mHelpContent = new javax.swing.JMenuItem();
        mCredits = new javax.swing.JMenuItem();
        mAbout = new javax.swing.JMenuItem();

        mPopNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mPopNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/page.png"))); // NOI18N
        mPopNew.setMnemonic('N');
        mPopNew.setText("Novo projeto");
        mPopNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNewActionPerformed(evt);
            }
        });
        popupMenuProject.add(mPopNew);

        mPopOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mPopOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_open-16.png"))); // NOI18N
        mPopOpen.setMnemonic('A');
        mPopOpen.setText("Abrir projeto");
        mPopOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOpenActionPerformed(evt);
            }
        });
        popupMenuProject.add(mPopOpen);

        mPopSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mPopSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_save-16.png"))); // NOI18N
        mPopSave.setMnemonic('S');
        mPopSave.setText("Salvar projeto");
        mPopSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSaveActionPerformed(evt);
            }
        });
        popupMenuProject.add(mPopSave);
        popupMenuProject.add(jSeparator7);

        mPopRename.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mPopRename.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/page_edit.png"))); // NOI18N
        mPopRename.setMnemonic('R');
        mPopRename.setText("Renomear projeto");
        mPopRename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRenameActionPerformed(evt);
            }
        });
        popupMenuProject.add(mPopRename);

        mPopClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mPopClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/page_delete.png"))); // NOI18N
        mPopClose.setMnemonic('F');
        mPopClose.setText("Fechar Projeto");
        mPopClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCloseActionPerformed(evt);
            }
        });
        popupMenuProject.add(mPopClose);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        toolBar.setRollover(true);

        bNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/page.png"))); // NOI18N
        bNew.setToolTipText("Novo projeto");
        bNew.setFocusable(false);
        bNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNewActionPerformed(evt);
            }
        });
        toolBar.add(bNew);

        bOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_open-16.png"))); // NOI18N
        bOpen.setToolTipText("Abrir projeto");
        bOpen.setFocusable(false);
        bOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOpenActionPerformed(evt);
            }
        });
        toolBar.add(bOpen);

        bSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_save-16.png"))); // NOI18N
        bSave.setToolTipText("Salvar projeto");
        bSave.setFocusable(false);
        bSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSaveActionPerformed(evt);
            }
        });
        toolBar.add(bSave);

        jSeparator5.setToolTipText("");
        jSeparator5.setSeparatorSize(new java.awt.Dimension(14, 28));
        toolBar.add(jSeparator5);

        bRename.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/page_edit.png"))); // NOI18N
        bRename.setToolTipText("Renomear projeto");
        bRename.setFocusable(false);
        bRename.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bRename.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bRename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRenameActionPerformed(evt);
            }
        });
        toolBar.add(bRename);

        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/page_delete.png"))); // NOI18N
        bClose.setToolTipText("Fechar projeto");
        bClose.setFocusable(false);
        bClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCloseActionPerformed(evt);
            }
        });
        toolBar.add(bClose);

        jSeparator3.setToolTipText("");
        jSeparator3.setSeparatorSize(new java.awt.Dimension(14, 28));
        toolBar.add(jSeparator3);

        bCodeGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/jsqlgen_logo.png"))); // NOI18N
        bCodeGen.setToolTipText("Gerar código");
        bCodeGen.setFocusable(false);
        bCodeGen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCodeGen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCodeGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCodeGenActionPerformed(evt);
            }
        });
        toolBar.add(bCodeGen);

        jSeparator4.setToolTipText("");
        jSeparator4.setSeparatorSize(new java.awt.Dimension(14, 28));
        toolBar.add(jSeparator4);

        bCut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_cut-16.png"))); // NOI18N
        bCut.setToolTipText("Recortar");
        bCut.setFocusable(false);
        bCut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCutActionPerformed(evt);
            }
        });
        toolBar.add(bCut);

        bCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_copy-16.png"))); // NOI18N
        bCopy.setToolTipText("Copiar");
        bCopy.setFocusable(false);
        bCopy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCopy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCopyActionPerformed(evt);
            }
        });
        toolBar.add(bCopy);

        bPaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_paste-16.png"))); // NOI18N
        bPaste.setToolTipText("Colar");
        bPaste.setFocusable(false);
        bPaste.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPaste.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPasteActionPerformed(evt);
            }
        });
        toolBar.add(bPaste);

        getContentPane().add(toolBar, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(pProjects, java.awt.BorderLayout.CENTER);

        mFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/cup.png"))); // NOI18N
        mFile.setMnemonic('A');
        mFile.setText("Arquivo");

        mNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/page.png"))); // NOI18N
        mNew.setMnemonic('N');
        mNew.setText("Novo projeto");
        mNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNewActionPerformed(evt);
            }
        });
        mFile.add(mNew);

        mOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_open-16.png"))); // NOI18N
        mOpen.setMnemonic('A');
        mOpen.setText("Abrir projeto");
        mOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOpenActionPerformed(evt);
            }
        });
        mFile.add(mOpen);

        mSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_save-16.png"))); // NOI18N
        mSave.setMnemonic('S');
        mSave.setText("Salvar projeto");
        mSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSaveActionPerformed(evt);
            }
        });
        mFile.add(mSave);

        mSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_save_as-16.png"))); // NOI18N
        mSaveAs.setMnemonic('C');
        mSaveAs.setText("Salvar projeto como");
        mSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSaveAsActionPerformed(evt);
            }
        });
        mFile.add(mSaveAs);
        mFile.add(jSeparator6);

        mRename.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mRename.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/page_edit.png"))); // NOI18N
        mRename.setMnemonic('R');
        mRename.setText("Renomear projeto");
        mRename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRenameActionPerformed(evt);
            }
        });
        mFile.add(mRename);

        mClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/page_delete.png"))); // NOI18N
        mClose.setMnemonic('F');
        mClose.setText("Fechar Projeto");
        mClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCloseActionPerformed(evt);
            }
        });
        mFile.add(mClose);
        mFile.add(jSeparator1);

        mCodeGen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        mCodeGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/jsqlgen_logo.png"))); // NOI18N
        mCodeGen.setMnemonic('G');
        mCodeGen.setText("Gerar Código");
        mCodeGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCodeGenActionPerformed(evt);
            }
        });
        mFile.add(mCodeGen);
        mFile.add(jSeparator2);

        mExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_exit-16.png"))); // NOI18N
        mExit.setMnemonic('r');
        mExit.setText("Sair");
        mExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitActionPerformed(evt);
            }
        });
        mFile.add(mExit);

        menuBar.add(mFile);

        mEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/server_edit.png"))); // NOI18N
        mEdit.setMnemonic('E');
        mEdit.setText("Editar");

        mCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mCut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_cut-16.png"))); // NOI18N
        mCut.setMnemonic('T');
        mCut.setText("Recortar");
        mCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCutActionPerformed(evt);
            }
        });
        mEdit.add(mCut);

        mCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_copy-16.png"))); // NOI18N
        mCopy.setMnemonic('I');
        mCopy.setText("Copiar");
        mCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCopyActionPerformed(evt);
            }
        });
        mEdit.add(mCopy);

        mPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        mPaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_paste-16.png"))); // NOI18N
        mPaste.setMnemonic('L');
        mPaste.setText("Colar");
        mPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPasteActionPerformed(evt);
            }
        });
        mEdit.add(mPaste);

        menuBar.add(mEdit);

        mHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/help.png"))); // NOI18N
        mHelp.setMnemonic('j');
        mHelp.setText("Ajuda");

        mHelpContent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        mHelpContent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/book.png"))); // NOI18N
        mHelpContent.setText("Conteúdo da ajuda");
        mHelpContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHelpContentActionPerformed(evt);
            }
        });
        mHelp.add(mHelpContent);

        mCredits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/brick.png"))); // NOI18N
        mCredits.setText("Créditos");
        mCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreditsActionPerformed(evt);
            }
        });
        mHelp.add(mCredits);

        mAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/information.png"))); // NOI18N
        mAbout.setText("Sobre");
        mAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAboutActionPerformed(evt);
            }
        });
        mHelp.add(mAbout);

        menuBar.add(mHelp);

        setJMenuBar(menuBar);

        setSize(new java.awt.Dimension(640, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /***************************/
    /***** Ações da Janela *****/

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        for(ProjectPanel projectForm: projectsForm){
            projectForm.refreshCoordinates();
        }
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        for(ProjectPanel projectForm: projectsForm){
            if(projectForm.isEdited()){
                int option = javax.swing.JOptionPane.showConfirmDialog(this, "O projeto "+projectForm.getProjectEdit().getName()+" foi modificado.\nDeseja salvar as alterações e sair?","Aviso",javax.swing.JOptionPane.YES_NO_CANCEL_OPTION);
                switch(option){
                    case(javax.swing.JOptionPane.YES_OPTION):
                        mSaveActionPerformed(null);
                        break;
                    case(javax.swing.JOptionPane.NO_OPTION):
                        break;
                    case(javax.swing.JOptionPane.CANCEL_OPTION):
                    case(javax.swing.JOptionPane.CLOSED_OPTION):
                        return;
                }
            }
        }
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void mExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitActionPerformed
        formWindowClosing(null);
    }//GEN-LAST:event_mExitActionPerformed

    /************************/
    /***** Menu Arquivo *****/

    private javax.swing.filechooser.FileFilter getFileFilter(){
        return new javax.swing.filechooser.FileFilter(){
            @Override
            public String getDescription(){
                return "JSQLGen 5 files (*.jsql5)";
            }
            @Override
            public boolean accept(java.io.File file){
                if(file.getName().endsWith(".jsql5") || file.isDirectory())
                    return true;
                else
                    return false;
            }

        };
    }

    private void mNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNewActionPerformed
        String projectName = javax.swing.JOptionPane.showInputDialog(this, "Nome do novo projeto:", "Novo projeto", javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (projectName != null && projectName.length() > 0) {
            project.Project projectEdit = new project.Project();
            ProjectPanel projectForm = new ProjectPanel(this, projectEdit);

            projectEdit.setName(projectName);
            projectEdit.getClassBeans().removeAll(projectEdit.getClassBeans());

            projectsForm.add(projectForm);
            pProjects.add(projectEdit.getName(), new javax.swing.JScrollPane(projectForm));
            pProjects.setSelectedIndex(pProjects.getTabCount()-1);

            //this.setTitle(projectName+" - JSQLGen "+version);
            refreshMenuOptions();
            repaint();
        }
    }//GEN-LAST:event_mNewActionPerformed

    private void mOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOpenActionPerformed
        //Inicia o navegador de arquivos
        javax.swing.JFileChooser browser = new javax.swing.JFileChooser();
        browser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
        browser.setMultiSelectionEnabled(false);
        browser.setCurrentDirectory(new java.io.File(currentDirectory));
        browser.setFileFilter(getFileFilter());

        //Exibe o navegador de arquivos, se o "Cancelar" for clicado retorna
        if (browser.showOpenDialog(this)==javax.swing.JFileChooser.CANCEL_OPTION)
            return;

        //Abre o arquivo
        String pathFile = browser.getSelectedFile().getAbsolutePath();
        try{
            project.Project projectEdit = new project.Project();
            projectEdit.loadXML(pathFile);
            ProjectPanel projectForm = new ProjectPanel(this, projectEdit);

            currentDirectory = browser.getSelectedFile().getAbsolutePath();
            //this.setTitle(browser.getSelectedFile().getName()+" - JSQLGen "+version);
            projectForm.refreshFrames();
            projectForm.repaint();
            projectForm.setEdited(false);
            projectForm.setCurrentDirectory(currentDirectory);
            
            projectsForm.add(projectForm);
            pProjects.add(projectEdit.getName(), new javax.swing.JScrollPane(projectForm));
            pProjects.setSelectedIndex(pProjects.getTabCount()-1);
            refreshMenuOptions();
        } catch (java.io.FileNotFoundException e){
            javax.swing.JOptionPane.showMessageDialog(this,"Arquivo inválido !");
        }
    }//GEN-LAST:event_mOpenActionPerformed

    private void mSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSaveActionPerformed
        if(pProjects.getSelectedIndex()>=0){
            ProjectPanel projectForm = projectsForm.get(pProjects.getSelectedIndex());
            project.Project projectEdit = projectForm.getProjectEdit();
            if(projectForm.getCurrentDirectory() !=null && !projectForm.getCurrentDirectory().isEmpty() && projectForm.getCurrentDirectory().compareTo("./")!=0){
                try{

                    projectEdit.saveXML(projectForm.getCurrentDirectory());
                    repaint();
                    projectForm.setEdited(false);
                } catch (java.io.FileNotFoundException e){
                    javax.swing.JOptionPane.showMessageDialog(this,"Arquivo inválido !");
                }
            } else {
                mSaveAsActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_mSaveActionPerformed

    private void mSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSaveAsActionPerformed
        if(pProjects.getSelectedIndex()>=0){
            //Inicia o navegador de arquivos
            ProjectPanel projectForm = projectsForm.get(pProjects.getSelectedIndex());
            project.Project projectEdit = projectForm.getProjectEdit();
            javax.swing.JFileChooser browser = new javax.swing.JFileChooser();
            browser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
            browser.setFileFilter(getFileFilter());
            browser.setMultiSelectionEnabled(false);
            browser.setCurrentDirectory(new java.io.File(projectForm.getCurrentDirectory()));
            browser.setSelectedFile(new java.io.File(projectEdit.getName()+".jsql5"));

            //Exibe o navegador de arquivos, se o "Cancelar" for clicado retorna
            if(browser.showSaveDialog(this)==javax.swing.JFileChooser.CANCEL_OPTION)
                return;

            //Se o arquivo selecionado não terminar com ".jsql5" adiciona o sufixo
            if(!browser.getSelectedFile().getName().endsWith(".jsql5"))
                browser.setSelectedFile(new java.io.File(browser.getSelectedFile().getAbsolutePath()+".jsql5"));

            //Se o arquivo selecionado existir pede a confirmação de substituição
            if(browser.getSelectedFile().exists())
                if(javax.swing.JOptionPane.showConfirmDialog(this, "Deseja substituir o arquivo?","Aviso",javax.swing.JOptionPane.OK_CANCEL_OPTION)==javax.swing.JOptionPane.CANCEL_OPTION)
                    return;

            //Salva o arquivo
            String pathFile = browser.getSelectedFile().getAbsolutePath();
            try{
                projectEdit.saveXML(pathFile);
                currentDirectory = browser.getSelectedFile().getAbsolutePath();
                //this.setTitle(browser.getSelectedFile().getName()+" - JSQLGen "+version);
                repaint();
                projectForm.setEdited(false);
                projectForm.setCurrentDirectory(currentDirectory);
            } catch (java.io.FileNotFoundException e){
                javax.swing.JOptionPane.showMessageDialog(this,"Arquivo inválido !");
            }
        }
    }//GEN-LAST:event_mSaveAsActionPerformed

    private void mCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCloseActionPerformed
        if(pProjects.getSelectedIndex()>=0){
            ProjectPanel projectForm = projectsForm.get(pProjects.getSelectedIndex());
            if(projectForm.isEdited()){
                int option = javax.swing.JOptionPane.showConfirmDialog(this, "O projeto "+projectForm.getProjectEdit().getName()+" foi modificado.\nDeseja salvar as alterações e fechar?","Aviso",javax.swing.JOptionPane.YES_NO_CANCEL_OPTION);
                switch(option){
                    case(javax.swing.JOptionPane.YES_OPTION):
                        mSaveActionPerformed(null);
                        break;
                    case(javax.swing.JOptionPane.NO_OPTION):
                        break;
                    case(javax.swing.JOptionPane.CANCEL_OPTION):
                    case(javax.swing.JOptionPane.CLOSED_OPTION):
                        return;            
                }
            }
            projectsForm.remove(pProjects.getSelectedIndex());
            pProjects.remove(pProjects.getSelectedIndex());
            refreshMenuOptions();
        }
    }//GEN-LAST:event_mCloseActionPerformed

    private void mRenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRenameActionPerformed
        if(pProjects.getSelectedIndex()>=0){
            ProjectPanel projectForm = projectsForm.get(pProjects.getSelectedIndex());
            project.Project projectEdit = projectForm.getProjectEdit();
            String projectName = javax.swing.JOptionPane.showInputDialog(this, "Nome do projeto:", projectEdit.getName());
            if (projectName != null && !projectName.isEmpty()) {
                projectEdit.setName(projectName);
                //this.setTitle(projectName+" - JSQLGen "+version);
                repaint();
                pProjects.setTitleAt(pProjects.getSelectedIndex(), projectEdit.getName());
                projectForm.setEdited(true);
            }
        }
    }//GEN-LAST:event_mRenameActionPerformed

    private void mCodeGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCodeGenActionPerformed
        if(pProjects.getSelectedIndex()>=0){
            ProjectPanel projectForm = projectsForm.get(pProjects.getSelectedIndex());
            project.Project projectEdit = projectForm.getProjectEdit();

            int n = projectEdit.isValid();
            if(n > 0){
                javax.swing.JOptionPane.showMessageDialog(this,"O projeto possui "+n+" classe(s) sem campo(s) único(s).\nAdicione os campos e tente novamente !");
                return;
            }
            if(projectEdit.getName().isEmpty())
                mRenameActionPerformed(evt);
            if(!projectEdit.getName().isEmpty() && !projectEdit.getClassBeans().isEmpty()){
                new ProjectGen(this, projectEdit, projectForm.getCurrentDirectory());
            }
        }
    }//GEN-LAST:event_mCodeGenActionPerformed

    /***********************/
    /***** Menu Editar *****/

    private void mCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCutActionPerformed
        if(pProjects.getSelectedIndex()>=0){
            ProjectPanel projectForm = projectsForm.get(pProjects.getSelectedIndex());
            projectForm.cut();
        }
    }//GEN-LAST:event_mCutActionPerformed

    private void mCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCopyActionPerformed
        if(pProjects.getSelectedIndex()>=0){
            ProjectPanel projectForm = projectsForm.get(pProjects.getSelectedIndex());
            projectForm.copy();
        }
    }//GEN-LAST:event_mCopyActionPerformed

    private void mPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPasteActionPerformed
        if(pProjects.getSelectedIndex()>=0){
            ProjectPanel projectForm = projectsForm.get(pProjects.getSelectedIndex());
            projectForm.paste();
        }
    }//GEN-LAST:event_mPasteActionPerformed

    /**********************/
    /***** Menu Ajuda *****/

    private void mHelpContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHelpContentActionPerformed
        java.awt.Desktop d = java.awt.Desktop.getDesktop();  
        try{  
            d.browse(new java.net.URI("https://sites.google.com/site/jsqlgen"));  
        } catch(java.io.IOException e) {  
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),"Error JSQLGen "+version,javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch(java.net.URISyntaxException e) {  
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),"Error JSQLGen "+version,javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mHelpContentActionPerformed

    private void mAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAboutActionPerformed
        String message = "";
        message += "JSQLGen\n\n" +
                   "Versão "+version+"\n" +
                   "Versão lançada em 11/11/2011\n" +
                   "Versão alterada em 30/10/2013\n" +
                   "Mantido pelo projeto SoLUC\n\n" +
                   "site:\n" +
                   "http://sites.google.com/site/projetosoluc\n" +
                   "http://sites.google.com/site/jsqlgen\n" +
                   "contato: info.cta.unesp@gmail.com\n\n" +
                   "© Copyright 2005~2013 Marcos Morise\n\n" +
                   "    JSQLGen é um software livre; você pode redistribuí-lo e/ou modificá-lo\n" +
                   "    dentro dos termos da Licença Pública Geral GNU como publicada \n" +
                   "    pela Fundação do Software Livre (FSF); na versão 3 da Licença.\n\n" +
                   "    JSQLGen é distribuido na esperança que possa ser util,\n" +
                   "    mas SEM NENHUMA GARANTIA; sem uma garantia implícita de \n" +
                   "    ADEQUAÇÂO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. \n\n" +
                   "    Veja a Licença Pública Geral GNU para maiores detalhes.\n" +
                   "    <http://www.gnu.org/licenses/>\n" +
                   "\n";
        javax.swing.JOptionPane.showMessageDialog(this, message,"About JSQLGen "+version,javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mAboutActionPerformed

    private void mCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCreditsActionPerformed
        java.awt.Desktop d = java.awt.Desktop.getDesktop();  
        try{  
            d.browse(new java.net.URI("https://sites.google.com/site/jsqlgen/creditos"));  
        } catch(java.io.IOException e) {  
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),"Error JSQLGen "+version,javax.swing.JOptionPane.ERROR_MESSAGE);
        }  
        catch(java.net.URISyntaxException e) {  
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),"Error JSQLGen "+version,javax.swing.JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_mCreditsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new JSQLGen5();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bCodeGen;
    private javax.swing.JButton bCopy;
    private javax.swing.JButton bCut;
    private javax.swing.JButton bNew;
    private javax.swing.JButton bOpen;
    private javax.swing.JButton bPaste;
    private javax.swing.JButton bRename;
    private javax.swing.JButton bSave;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JMenuItem mAbout;
    private javax.swing.JMenuItem mClose;
    private javax.swing.JMenuItem mCodeGen;
    private javax.swing.JMenuItem mCopy;
    private javax.swing.JMenuItem mCredits;
    private javax.swing.JMenuItem mCut;
    private javax.swing.JMenu mEdit;
    private javax.swing.JMenuItem mExit;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenuItem mHelpContent;
    private javax.swing.JMenuItem mNew;
    private javax.swing.JMenuItem mOpen;
    private javax.swing.JMenuItem mPaste;
    private javax.swing.JMenuItem mPopClose;
    private javax.swing.JMenuItem mPopNew;
    private javax.swing.JMenuItem mPopOpen;
    private javax.swing.JMenuItem mPopRename;
    private javax.swing.JMenuItem mPopSave;
    private javax.swing.JMenuItem mRename;
    private javax.swing.JMenuItem mSave;
    private javax.swing.JMenuItem mSaveAs;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTabbedPane pProjects;
    private javax.swing.JPopupMenu popupMenuProject;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
